# Data Science Project 1
## Advanced EDA & Feature Engineering

In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv("Dataset for Data Analytics - Sheet1.csv")

In [3]:
df.head()

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
0,ORD200000,2023-01-04,C72649,Monitor,5,570.62,928 Main St,Debit Card,Shipped,TRK37947903,7,SAVE10,Instagram,2853.10
1,ORD200001,2024-08-23,C75739,Phone,2,151.35,823 Main St,Online,Shipped,TRK91186779,3,SAVE10,Referral,302.70
2,ORD200002,2024-02-27,C81728,Tablet,5,550.68,512 Main St,Credit Card,Cancelled,TRK42903982,8,FREESHIP,Email,2753.40
3,ORD200003,2023-10-15,C33540,Chair,1,273.19,275 Main St,Debit Card,Returned,TRK62788070,5,SAVE10,Facebook,273.19
4,ORD200004,2025-05-08,C81840,Printer,4,626.01,668 Main St,Online,Delivered,TRK29241424,8,SAVE10,Email,2504.04

In [4]:
df.shape

(1200, 14)

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   OrderID          1200 non-null   str
 1   Date             1200 non-null   str
 2   CustomerID       1200 non-null   str
 3   Product          1200 non-null   str
 4   Quantity         1200 non-null   int64
 5   UnitPrice        1200 non-null   float64
 6   ShippingAddress  1200 non-null   str
 7   PaymentMethod    1200 non-null   str
 8   OrderStatus      1200 non-null   str
 9   TrackingNumber   1200 non-null   str
 10  ItemsInCart      1200 non-null   int64
 11  CouponCode       891 non-null    str
 12  ReferralSource   1200 non-null   str
 13  TotalPrice       1200 non-null   float64
dtypes: float64(2), int64(2), str(10)
memory usage: 226.8 KB

In [9]:
df.isnull().sum()

OrderID              0
Date                 0
CustomerID           0
Product              0
Quantity             0
UnitPrice            0
ShippingAddress      0
PaymentMethod        0
OrderStatus          0
TrackingNumber       0
ItemsInCart          0
CouponCode         309
ReferralSource       0
TotalPrice           0
dtype: int64

In [11]:
df["CouponCode"]=df["CouponCode"].fillna("No Coupon")

In [12]:
df.isnull().sum()

OrderID            0
Date               0
CustomerID         0
Product            0
Quantity           0
UnitPrice          0
ShippingAddress    0
PaymentMethod      0
OrderStatus        0
TrackingNumber     0
ItemsInCart        0
CouponCode         0
ReferralSource     0
TotalPrice         0
dtype: int64

In [13]:
df.describe()

          Quantity    UnitPrice  ItemsInCart   TotalPrice
count  1200.000000  1200.000000  1200.000000  1200.000000
mean      2.945833   356.412750     5.485000  1053.968300
std       1.407557   197.177146     2.281983   819.856558
min       1.000000    11.390000     1.000000    11.390000
25%       2.000000   186.062500     4.000000   410.520000
50%       3.000000   364.210000     5.000000   823.615000
75%       4.000000   521.570000     7.000000  1578.475000
max       5.000000   699.930000    10.000000  3456.400000

In [15]:
Q1=df[["Quantity","UnitPrice","ItemsInCart","TotalPrice"]].quantile(0.25)
Q3=df[["Quantity","UnitPrice","ItemsInCart","TotalPrice"]].quantile(0.75)

IQR=Q3-Q1
lower_bound= Q1-1.5*IQR
upper_bound= Q3+1.5*IQR

print("Lower Bound:")
print(lower_bound)

print("\nUpper Bound:")
print(upper_bound)

Lower Bound:
Quantity         -1.00000
UnitPrice      -317.19875
ItemsInCart      -0.50000
TotalPrice    -1341.41250
dtype: float64

Upper Bound:
Quantity          7.00000
UnitPrice      1024.83125
ItemsInCart      11.50000
TotalPrice     3330.40750
dtype: float64

In [16]:
numeric_cols=["Quantity","UnitPrice","ItemsInCart","TotalPrice"]
for col in numeric_cols:
    outliers=df[(df[col]<lower_bound[col]) | (df[col]>upper_bound[col])]
    print(col, ":", len(outliers),"outliers")

Quantity : 0 outliers
UnitPrice : 0 outliers
ItemsInCart : 0 outliers
TotalPrice : 8 outliers

In [9]:
outliers_totalprice = df[
    (df["TotalPrice"] < lower_bound["TotalPrice"]) |
    (df["TotalPrice"] > upper_bound["TotalPrice"])
]
outliers_totalprice

NameError: name 'df' is not defined

In [10]:
import pandas as pd
import numpy as np

df = pd.read_csv("Dataset for Data Analytics - Sheet1.csv")

In [11]:
df.shape

(1200, 14)

In [12]:
numeric_cols = ["Quantity", "UnitPrice", "ItemsInCart", "TotalPrice"]

Q1 = df[numeric_cols].quantile(0.25)
Q3 = df[numeric_cols].quantile(0.75)

IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

In [13]:
outliers_totalprice = df[
    (df["TotalPrice"] < lower_bound["TotalPrice"]) |
    (df["TotalPrice"] > upper_bound["TotalPrice"])
]

outliers_totalprice

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
107,ORD200107,2023-03-27,C16775,Printer,5,670.75,848 Main St,Gift Card,Shipped,TRK34392124,8,FREESHIP,Instagram,3353.75
326,ORD200326,2024-07-01,C65986,Laptop,5,670.48,273 Main St,Gift Card,Returned,TRK98353867,5,SAVE10,Facebook,3352.40
328,ORD200328,2023-02-28,C18404,Tablet,5,674.04,546 Main St,Online,Cancelled,TRK89401624,7,SAVE10,Google,3370.20
469,ORD200469,2023-11-26,C13877,Chair,5,676.98,893 Main St,Cash,Cancelled,TRK17254691,5,NaN,Facebook,3384.90
632,ORD200632,2023-05-02,C67260,Laptop,5,678.16,463 Main St,Gift Card,Delivered,TRK38229104,7,WINTER15,Facebook,3390.80
789,ORD200789,2023-08-17,C57276,Tablet,5,691.28,183 Main St,Online,Delivered,TRK75899752,10,SAVE10,Email,3456.40
1065,ORD201065,2023-10-30,C47778,Printer,5,666.80,488 Main St,Debit Card,Delivered,TRK79504329,7,SAVE10,Referral,3334.00
1122,ORD201122,2023-06-07,C38840,Monitor,5,678.19,766 Main St,Online,Returned,TRK32496970,8,NaN,Facebook,3390.95

In [14]:
df["CouponCode"] = df["CouponCode"].fillna("No Coupon")

In [15]:
df["CouponCode"].isnull().sum()

np.int64(0)

In [17]:
df["TotalPrice"]=df["TotalPrice"].clip(upper_bound["TotalPrice"])

In [18]:
df["TotalPrice"].max()

np.float64(3456.4)

In [19]:
upper_bound["TotalPrice"]

np.float64(3330.4075)

In [20]:
df["TotalPrice"] = df["TotalPrice"].clip(upper=upper_bound["TotalPrice"])

In [21]:
df["TotalPrice"].max()

np.float64(3330.4075)

In [22]:
df["HasCoupon"] = (df["CouponCode"] != "No Coupon").astype(int)

In [23]:
df[["CouponCode", "HasCoupon"]].head(10)

  CouponCode  HasCoupon
0     SAVE10          1
1     SAVE10          1
2   FREESHIP          1
3     SAVE10          1
4     SAVE10          1
5     SAVE10          1
6     SAVE10          1
7   FREESHIP          1
8  No Coupon          0
9     SAVE10          1

In [24]:
df["PricePerItem"] = df["TotalPrice"] / df["Quantity"]

In [25]:
df[["TotalPrice", "Quantity", "PricePerItem"]].head()

   TotalPrice  Quantity  PricePerItem
0   3330.4075         5    666.081500
1   3330.4075         2   1665.203750
2   3330.4075         5    666.081500
3   3330.4075         1   3330.407500
4   3330.4075         4    832.601875

In [26]:
df["CartUtilization"] = df["Quantity"] / df["ItemsInCart"]

In [27]:
df[["Quantity", "ItemsInCart", "CartUtilization"]].head()

   Quantity  ItemsInCart  CartUtilization
0         5            7         0.714286
1         2            3         0.666667
2         5            8         0.625000
3         1            5         0.200000
4         4            8         0.500000

In [28]:
df.isnull().sum()

OrderID            0
Date               0
CustomerID         0
Product            0
Quantity           0
UnitPrice          0
ShippingAddress    0
PaymentMethod      0
OrderStatus        0
TrackingNumber     0
ItemsInCart        0
CouponCode         0
ReferralSource     0
TotalPrice         0
HasCoupon          0
PricePerItem       0
CartUtilization    0
dtype: int64

In [29]:
df.shape

(1200, 17)

In [30]:
df.to_csv("Project_1_Cleaned.csv", index=False)

In [31]:
import os
os.path.exists("Project_1_Cleaned.csv")

True

In [32]:
df.head()

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice,HasCoupon,PricePerItem,CartUtilization
0,ORD200000,2023-01-04,C72649,Monitor,5,570.62,928 Main St,Debit Card,Shipped,TRK37947903,7,SAVE10,Instagram,3330.4075,1,666.081500,0.714286
1,ORD200001,2024-08-23,C75739,Phone,2,151.35,823 Main St,Online,Shipped,TRK91186779,3,SAVE10,Referral,3330.4075,1,1665.203750,0.666667
2,ORD200002,2024-02-27,C81728,Tablet,5,550.68,512 Main St,Credit Card,Cancelled,TRK42903982,8,FREESHIP,Email,3330.4075,1,666.081500,0.625000
3,ORD200003,2023-10-15,C33540,Chair,1,273.19,275 Main St,Debit Card,Returned,TRK62788070,5,SAVE10,Facebook,3330.4075,1,3330.407500,0.200000
4,ORD200004,2025-05-08,C81840,Printer,4,626.01,668 Main St,Online,Delivered,TRK29241424,8,SAVE10,Email,3330.4075,1,832.601875,0.500000